### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [joseahr/sig_betera_server#1]
this type of code is bad:

``` js
            perms : `{${pgp.as.value(perms.join())}}`
```

you should change your sql from `ANY(${perms})` to `ANY(${perms:csv})` and pass in array of values directly ;)

**Comment by joseahr** [comment]
Hey! Thank you for your tips. I've wrote this : 

`ANY(ARRAY[${perms:csv}]::roles_enum[]);`

**Comment by vitaly-t** [comment]
I believe that `ANY(${perms:csv})` should have sufficed, unless you are using custom data types.

**Comment by joseahr** [comment]
If I use:

```
rep.manyOrNone(sql.getLayerNamesByPerms, {
    id_user : pgp.as.value(id_user),
    perms   : pgp.as.value(perms)
})
```

And the SQL:

```
SELECT r.*, ly.name FROM Roles r
LEFT JOIN Layers ly ON r.id_layer = ly.id
WHERE id_user = ${id_user} AND rol = ANY(${perms:csv});
```

The query formatted is:
`query: SELECT r.*, ly.name FROM Roles r LEFT JOIN Layers ly ON r.id_layer = ly.id WHERE id_user = '1' AND rol = ANY('array[''''r'''',''''e'''',''''d'''']');`
and the error i'm getting:
`error: array literal is not valid: «array[''r'',''e'',''d'']»`

What i'm doing wrong?

**Comment by vitaly-t** [comment]
You are misusing method `value` it is not what's there for. You are supposed to pass in the values directly and use formatting modifiers where applicable.

It is again what I wrote you in the very beginning.

**Comment by joseahr** [comment]
Sorry again! If I pass an array of values directly (perms) then the query formatted is wrong:
`SELECT r.*, ly.name FROM Roles r LEFT JOIN Layers ly ON r.id_layer = ly.id WHERE id_user = '1' AND rol = ANY('r','e','d');`
it should be:
`ANY('{r,e,d}');`

**Comment by vitaly-t** [comment]
`ANY('{r,e,d}')` isn't a valid SQL.

**Comment by joseahr** [comment]
Using this seems to work:

```
rep.manyOrNone(sql.getLayerNamesByPerms, {
    id_user : pgp.as.value(id_user),
    perms   : `{${perms}}`
})
```
But I don't know if it's the propper way.

**Comment by joseahr** [comment]
Using psql:

```
betera-test=# SELECT r.*, ly.name FROM ROLES r LEFT JOIN LAYERS ly ON r.id_layer = ly.id WHERE id_user = '1' AND rol = ANY('{r, e, d}');
 id_user | id_layer | rol |        name        
---------+----------+-----+--------------------
       1 |        1 | r   | callejero
       1 |        2 | e   | catastro_historico
       1 |        3 | d   | envases
```

This syntax seems to be working.
Using what you say formats the query incorrectly `ANY('r','e','d')` which gives me a syntax error. 
Finally I've decided to use `IN` instead of `ANY`:

```
SELECT r.*, ly.name FROM Roles r
LEFT JOIN Layers ly ON r.id_layer = ly.id
WHERE id_user = ${id_user} AND rol IN (${perms:csv});
```

and pass in an array directly.

**Comment by vitaly-t** [comment]
instead of using this:

``` js
geomColumn : pgp.as.name(geomColumn.name),
```

you can use `geomColumn.name` directly, and change your SQL from `${geomColumn^}` to `${geomColumn~}` ;)
